### Система рекоммендации постов

### Загрузка библиотек и наьборов данных

In [1]:
import numpy as np
import pandas as pd
post = pd.read_csv('posts.csv')
user = pd.read_csv('users.csv')
view = pd.read_csv('views.csv')

### Обзор данных и предобработка

In [2]:
user.head()

                        _id                  name gender      academics
0  5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
1  5d610ae1653a331687083239         Gaurav Sharma   male       graduate
2  5d618359fc5fcf3bdd9a0910         Akshay Mishra   male  undergraduate
3  5d6d2bb87fa40e1417a49315        Saksham Mathur   male  undergraduate
4  5d7c994d5720533e15c3b1e9         Varun Chowhan   male  undergraduate

In [4]:
post.head(20)

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence|Machine Learning|Infor...,blog
2,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog
3,5d7d405e5720533e15c3b1f3,Lord Shiva,Drawings,artwork
4,5d80dfbc6c53455f896e600e,How Competition law evolved?,Competition Laws,blog
5,5d80e7c16c53455f896e6014,Raghavan Committee - 2002.,Competition Laws,blog
6,5d80ecfd6c53455f896e601a,Let's discuss some Case laws!,Competition Laws,blog
7,5d81323a6c53455f896e6044,Forms of Cartel.,Competition Laws,blog
8,5d9b3514979d5962253c2f90,Biodiversity,Eco System,blog
9,5d9b950768671220a1b2b153,Economic policy,Economic Policies,blog
10,5da745b6019399436815c4cd,Corporate design,Graphic|Graphic Design,artwork
11,5dada695610ba040fbfdf585,Trident,Drawings,artwork
12,5dada734610ba040fbfdf588,Lord shiva,Drawings,artwork
13,5dada798610ba040fbfdf58b,Smart City,Painting,artwork
14,5dada82f610ba040fbfdf58e,Om Namah Shivaay,Pen and ink,artwork
15,5dada89b610ba040fbfdf591,Kid Bu,Drawings,artwork
16,5dadf6ae610ba040fbfdf5c8,MIS,Computer Technology|Information Technology,blog
17,5db2a7d099cbb90e4339c734,Portrait art,Drawings|Painting,artwork
18,5db2b91a99cbb90e4339c749,CLASSIFYING FORMS OF CARTELS,Competition Laws,blog
19,5dbc622a99cbb90e4339c7f6,Best friend,Graphic Design|Visual Arts|Illustration|Graphic,artwork

In [6]:
view.head(20)

,user_id,post_id,timestamp
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z
1,5ed3748576027d35905ccaab,5ed4cbadbd514d602c1531a6,2020-06-01T09:39:20.021Z
2,5ed0defa76027d35905cc2de,5eac305f10426255a7aa9dd3,2020-06-01T08:12:42.682Z
3,5ed0defa76027d35905cc2de,5ed1ff0276027d35905cc60d,2020-06-01T08:10:23.880Z
4,5ed0defa76027d35905cc2de,5ed3820f76027d35905ccac8,2020-06-01T08:08:54.124Z
5,5ed0defa76027d35905cc2de,5ed23d4276027d35905cc798,2020-06-01T08:07:22.659Z
6,5ed0defa76027d35905cc2de,5ed415c6bd514d602c15312d,2020-06-01T08:07:01.935Z
7,5ecb979eeaff6b0c3a58a4f0,5ed229d976027d35905cc666,2020-05-31T20:44:07.524Z
8,5ecb979eeaff6b0c3a58a4f0,5ed2502b76027d35905cc7db,2020-05-31T20:43:17.623Z
9,5ecb979eeaff6b0c3a58a4f0,5ed13d2876027d35905cc4c2,2020-05-31T20:42:38.962Z
10,5ecb979eeaff6b0c3a58a4f0,5ed3476576027d35905cca1d,2020-05-31T20:41:30.667Z
11,5ecb979eeaff6b0c3a58a4f0,5ed3820f76027d35905ccac8,2020-05-31T20:40:18.693Z
12,5ecb979eeaff6b0c3a58a4f0,5ed3791976027d35905ccab6,2020-05-31T20:39:46.665Z
13,5ecb979eeaff6b0c3a58a4f0,5ed415c6bd514d602c15312d,2020-05-31T20:38:57.493Z
14,5ecb979eeaff6b0c3a58a4f0,5ed3ef4cbd514d602c1530f2,2020-05-31T19:06:06.841Z
15,5ed3e898bd514d602c1530de,5ecf818376027d35905cbf03,2020-05-31T18:56:56.215Z
16,5d60098a653a331687083238,5ed3820f76027d35905ccac8,2020-05-31T18:01:54.308Z
17,5ed3cbcbbd514d602c1530a7,5ed1ff0276027d35905cc60d,2020-05-31T16:16:51.523Z
18,5ece02427023451e66223861,5ed09ad076027d35905cc15f,2020-05-31T14:48:47.214Z
19,5ecb979eeaff6b0c3a58a4f0,5ecfb35c76027d35905cbfbc,2020-05-31T14:20:35.175Z

In [7]:
user.shape, post.shape, view.shape

((118, 4), (493, 4), (1449, 3))

In [8]:
user.describe()

                             _id                  name gender      academics
count                        118                   118    118            118
unique                       118                   118      3              3
top     5d60098a653a331687083238  Nivesh Singh Chauhan   male  undergraduate
freq                           1                     1     72             68

In [10]:
user['gender'].value_counts()

gender
male         72
female       44
undefined     2
Name: count, dtype: int64

In [11]:
post.describe()

                             _id             title     category  post_type
count                        493               493          465        493
unique                       493               477          231          4
top     5d62abaa65218653a132c956  PENCIL RENDERING  Photography    artwork
freq                           1                 3           81        241

In [12]:
view.describe()

,user_id,post_id,timestamp
count,1449,1449,1449
unique,118,495,1449
top,5d60098a653a331687083238,5ec1fd0974f7660d73aa0fd5,2020-06-01T10:46:45.131Z
freq,230,18,1

In [13]:
user.isna().sum()

_id          0
name         0
gender       0
academics    0
dtype: int64

In [14]:
post.isna().sum()

_id            0
title          0
category      28
 post_type     0
dtype: int64

In [15]:
view.isna().sum()

user_id      0
post_id      0
timestamp    0
dtype: int64

In [16]:
post[post['category'].isna()]

,_id,title,category,post_type
24,5ddeb6e80eb5e25a8a07f065,Library Managment System: Software Requirement...,NaN,project
25,5de179d80eb5e25a8a07f079,Navigation system using BFS DFS algorithms,NaN,project
29,5dee9b5042a8854bf6eabaaf,Computer Aided Machine Drawing (CAMD),NaN,project
65,5e3ea110eab55d319938a7a7,OS,NaN,project
88,5e4c3873f5561b1994c8e3d9,Bill Calculation(PHP),NaN,project
93,5e4da502f5561b1994c8e42c,Prime No.(PHP),NaN,project
94,5e4da7c8f5561b1994c8e439,Factorial of a No.(PHP),NaN,project
95,5e4dab15f5561b1994c8e446,Palindrome No.(PHP),NaN,project
96,5e4ed85af5561b1994c8e470,Factorial (.net),NaN,project
97,5e4ed8ccf5561b1994c8e47d,Leap year checking (.net),NaN,project
98,5e4edd1bf5561b1994c8e48a,Delegates(.net),NaN,project
99,5e4edd87f5561b1994c8e497,Overloading Method(.net),NaN,project
227,5e8c2d01a3258347b42f2627,Even and Odd Numbers (PHP),NaN,project
228,5e8c993da3258347b42f264d,Armstrong No.(C# .Net),NaN,project
229,5e8cb88ea3258347b42f267e,Palindrome (C# .Net),NaN,project
230,5e8cc876a3258347b42f26a3,Negative or Positive No. (PHP),NaN,project
231,5e8ccfb5a3258347b42f26bc,Friend Number (C# .Net),NaN,project
352,5ea5aacd10426255a7aa9b71,Photography Composition,NaN,project
353,5ea5ce9310426255a7aa9b8d,Photography,NaN,project
374,5eaf3d4110426255a7aa9f4c,Students Networking!,NaN,blog
394,5eb1df6d10426255a7aaa029,Novel & Consenent (P.H.P),NaN,project
442,5eca8fceeaff6b0c3a58a3c0,Zero-Waste Lifestyle,NaN,project
463,5ed0e31a76027d35905cc302,Designing Cmos circuit from Boolean expression...,NaN,project
464,5ed0e65976027d35905cc356,Moore FSM Sequence Detector,NaN,project
465,5ed0f0c576027d35905cc3c7,Designing Circular Microstrip Antenna,NaN,project
468,5ed175f176027d35905cc554,GAN's Introduction,NaN,project
469,5ed175f476027d35905cc562,GAN's Introduction,NaN,project
490,5ed3ef4cbd514d602c1530f2,Recommendation Engine,NaN,project

In [17]:
post['category'].unique()

<ArrowStringArray>
[                                                 'Plant Biotechnology',
      'Artificial Intelligence|Machine Learning|Information Technology',
                                                    'Operating Systems',
                                                             'Drawings',
                                                     'Competition Laws',
                                                           'Eco System',
                                                    'Economic Policies',
                                               'Graphic|Graphic Design',
                                                             'Painting',
                                                          'Pen and ink',
 ...
                                                           'Technology',
 'Computer Technology|Computation|Computer Application|Cloud Computing',
                                  'Visual Arts|Calligraphy|Pen and ink',
                                  'Mixed Media|Calligraphy|Pen and ink',
                                               'Typography|Pen and ink',
                                   'Typography|Calligraphy|Pen and ink',
                                   'Calligraphy|Typography|Pen and ink',
                                              'Calligraphy|Pen and ink',
                                         'Mass Media|Media And Society',
                                                  'Science; Technology']
Length: 232, dtype: str

In [18]:
post['category'] = post['category'].fillna('random')

In [19]:
post.isna().sum()

_id           0
title         0
category      0
 post_type    0
dtype: int64

### Словарь: категория - значение

In [20]:
cat = {}
for i in post['category']:
    cat.update({i:[]})
    for j in i.split('|'):
        cat[i].append(j)
print(cat)

{'Plant Biotechnology': ['Plant Biotechnology'], 'Artificial Intelligence|Machine Learning|Information Technology': ['Artificial Intelligence', 'Machine Learning', 'Information Technology'], 'Operating Systems': ['Operating Systems'], 'Drawings': ['Drawings'], 'Competition Laws': ['Competition Laws'], 'Eco System': ['Eco System'], 'Economic Policies': ['Economic Policies'], 'Graphic|Graphic Design': ['Graphic', 'Graphic Design'], 'Painting': ['Painting'], 'Pen and ink': ['Pen and ink'], 'Computer Technology|Information Technology': ['Computer Technology', 'Information Technology'], 'Drawings|Painting': ['Drawings', 'Painting'], 'Graphic Design|Visual Arts|Illustration|Graphic': ['Graphic Design', 'Visual Arts', 'Illustration', 'Graphic'], 'Drawings|Calligraphy': ['Drawings', 'Calligraphy'], 'Photography': ['Photography'], 'Empowerment': ['Empowerment'], 'random': ['random'], 'Video editing': ['Video editing'], 'Inorganic Chemistry': ['Inorganic Chemistry'], 'Programming languages': ['Programming languages'], 'Conceptual|Graphic Design': ['Conceptual', 'Graphic Design'], 'HR Management': ['HR Management'], 'Human Resources|HR Management': ['Human Resources', 'HR Management'], 'Mass Media|International Relations': ['Mass Media', 'International Relations'], 'Sculptures|Artistic design': ['Sculptures', 'Artistic design'], 'Fashion Design|Ceramics|Artistic design': ['Fashion Design', 'Ceramics', 'Artistic design'], 'Craft|Artistic design': ['Craft', 'Artistic design'], 'Fashion Design|Visual Arts|Conceptual|Artistic design': ['Fashion Design', 'Visual Arts', 'Conceptual', 'Artistic design'], 'Photography|Fashion Design|Visual Arts|Graphic Design|Artistic design': ['Photography', 'Fashion Design', 'Visual Arts', 'Graphic Design', 'Artistic design'], 'Fashion Design|Visual Arts|Graphic Design|Artistic design|Graphic|Illustration': ['Fashion Design', 'Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Illustration'], 'Mathematics|Linear Algebra': ['Mathematics', 'Linear Algebra'], 'Electronics & electrical Technology|Electrical Machines': ['Electronics & electrical Technology', 'Electrical Machines'], 'Auditing|Internal Audit': ['Auditing', 'Internal Audit'], 'E Commerce|E Transactions': ['E Commerce', 'E Transactions'], 'Computer Technology|Computation': ['Computer Technology', 'Computation'], 'Auditing|Internal Financial Control': ['Auditing', 'Internal Financial Control'], 'Taxation|Custom Laws': ['Taxation', 'Custom Laws'], 'Auditing|Audit Evidence': ['Auditing', 'Audit Evidence'], 'Taxation|GST': ['Taxation', 'GST'], 'Taxation|Direct Tax': ['Taxation', 'Direct Tax'], 'Auditing|Secratarial Audit': ['Auditing', 'Secratarial Audit'], 'Banking|Banking Companies': ['Banking', 'Banking Companies'], 'Banking|Banking Technology': ['Banking', 'Banking Technology'], 'Auditing|Audit Remark': ['Auditing', 'Audit Remark'], 'Auditing|Cost Audit': ['Auditing', 'Cost Audit'], 'Auditing|Statuary Audit': ['Auditing', 'Statuary Audit'], 'Computer Technology|Programming languages': ['Computer Technology', 'Programming languages'], 'Legal Studies|Legal System': ['Legal Studies', 'Legal System'], 'Sports Coaching|Sports Law': ['Sports Coaching', 'Sports Law'], 'Economics|Economics Sociology': ['Economics', 'Economics Sociology'], 'Economics|Revenue Concept': ['Economics', 'Revenue Concept'], 'Human Rights|Rights and Duties': ['Human Rights', 'Rights and Duties'], 'Sociology|Sociology of Religion': ['Sociology', 'Sociology of Religion'], 'Sociology|Sociology in India': ['Sociology', 'Sociology in India'], 'Political Science|International Politics': ['Political Science', 'International Politics'], 'Political Science|Colonialism In India': ['Political Science', 'Colonialism In India'], 'Legal Studies|Labor Law': ['Legal Studies', 'Labor Law'], 'Computer Technology|Design and Analysis of Algorithms|Programming languages': ['Computer Technology', 'Design and Analysis of Algorithms', 'Programming languages'], 'Computer Technology|Computer Application|Programming languages|Information Technology': ['Computer Technology', 'Computer Application', 'Programming languages', 'Information Technology'], 'Graphics|Computer Creation': ['Graphics', 'Computer Creation'], 'E Commerce|Other Online Platforms': ['E Commerce', 'Other Online Platforms'], 'Drawing': ['Drawing'], 'Drawings|Artistic design': ['Drawings', 'Artistic design'], 'Drawings|Artistic design|Illustration': ['Drawings', 'Artistic design', 'Illustration'], 'E Commerce|Shopping Platform|Other Online Platforms': ['E Commerce', 'Shopping Platform', 'Other Online Platforms'], 'Computer Technology|Hardware|Information Technology': ['Computer Technology', 'Hardware', 'Information Technology'], 'Computer Technology|Computation|Computer Application': ['Computer Technology', 'Computation', 'Computer Application'], 'Business|Business Skills': ['Business', 'Business Skills'], 'Computer Technology|Computer Application|Hardware|Information Technology': ['Computer Technology', 'Computer Application', 'Hardware', 'Information Technology'], 'Computer Technology|Computer Application': ['Computer Technology', 'Computer Application'], 'Computer Technology|Mobile Applications': ['Computer Technology', 'Mobile Applications'], 'Computer Technology|Computer Application|Operating Systems': ['Computer Technology', 'Computer Application', 'Operating Systems'], 'Computer Technology|Information Technology|Computer Application': ['Computer Technology', 'Information Technology', 'Computer Application'], 'Computer Technology|Computer Application|Information Technology': ['Computer Technology', 'Computer Application', 'Information Technology'], 'Communication|Basics of Communiaction': ['Communication', 'Basics of Communiaction'], 'Drawings|Painting|Visual Arts|Graphic Design|Prints|Illustration': ['Drawings', 'Painting', 'Visual Arts', 'Graphic Design', 'Prints', 'Illustration'], 'Drawings|Visual Arts|Painting|Graphic Design|Artistic design|Illustration': ['Drawings', 'Visual Arts', 'Painting', 'Graphic Design', 'Artistic design', 'Illustration'], 'Computer Technology|Artificial Intelligence': ['Computer Technology', 'Artificial Intelligence'], 'Marketing|Advertising': ['Marketing', 'Advertising'], 'Political Science|Political Thought': ['Political Science', 'Political Thought'], 'Accounting|Fundamental Of Accounting': ['Accounting', 'Fundamental Of Accounting'], 'Mixed Media': ['Mixed Media'], 'Management|Team Mangememnt': ['Management', 'Team Mangememnt'], 'Business|Corporate Social Responsibilities': ['Business', 'Corporate Social Responsibilities'], 'Philosophy|Applied Ethics': ['Philosophy', 'Applied Ethics'], 'Human Resources|Performance In Organization|Organizational Behaviour|HR Management': ['Human Resources', 'Performance In Organization', 'Organizational Behaviour', 'HR Management'], 'Fashion Desigining|Fashion Textile|Fashion Manufacturing|Fashion Techniques|Garment Production|Garment Technology': ['Fashion Desigining', 'Fashion Textile', 'Fashion Manufacturing', 'Fashion Techniques', 'Garment Production', 'Garment Technology'], 'Marketing|Promotion And Distribution Decisions': ['Marketing', 'Promotion And Distribution Decisions'], 'Biotechnology|Genetic Engineering': ['Biotechnology', 'Genetic Engineering'], 'Physiology|Neurology': ['Physiology', 'Neurology'], 'Mass Media|Indian Government': ['Mass Media', 'Indian Government'], 'Physiology|Osteology': ['Physiology', 'Osteology'], 'Physiology|Cardiology': ['Physiology', 'Cardiology'], 'Zoology|Ecology': ['Zoology', 'Ecology'], 'Computer Technology|Cloud Computing': ['Computer Technology', 'Cloud Computing'], 'Physiology|Radiology': ['Physiology', 'Radiology'], 'Computer Technology|Operating Systems': ['Computer Technology', 'Operating Systems'], 'Biotechnology|Molecular Biology': ['Biotechnology', 'Molecular Biology'], 'Physiology|Gastroenterology|Cardiology': ['Physiology', 'Gastroenterology', 'Cardiology'], 'Philosophy|Logic': ['Philosophy', 'Logic'], 'Watercolours': ['Watercolours'], 'Drawings|Watercolours': ['Drawings', 'Watercolours'], 'Mixed Media|Conceptual': ['Mixed Media', 'Conceptual'], 'Drawings|Painting|Watercolours': ['Drawings', 'Painting', 'Watercolours'], 'Visual Arts': ['Visual Arts'], 'Conceptual': ['Conceptual'], 'Tapestry': ['Tapestry'], 'Calligraphy': ['Calligraphy'], 'Human Resources|Performance In Organization': ['Human Resources', 'Performance In Organization'], 'Computer Technology|Robotics|Data Science|Information Technology|Artificial Intelligence': ['Computer Technology', 'Robotics', 'Data Science', 'Information Technology', 'Artificial Intelligence'], 'Philosophy|Public Philosophy': ['Philosophy', 'Public Philosophy'], 'Digital Marketing': ['Digital Marketing'], 'Mass Media|Videography': ['Mass Media', 'Videography'], 'Drawings|Painting|Visual Arts|Artistic design|Watercolours|Acrylics': ['Drawings', 'Painting', 'Visual Arts', 'Artistic design', 'Watercolours', 'Acrylics'], 'Biotechnology|Plant Biotechnology': ['Biotechnology', 'Plant Biotechnology'], 'Sports Coaching|Sports Event': ['Sports Coaching', 'Sports Event'], 'Political Science|Government and Politics': ['Political Science', 'Government and Politics'], 'Geography|Physical Geography': ['Geography', 'Physical Geography'], 'Computer Technology|Data Science': ['Computer Technology', 'Data Science'], 'Computer Technology|Machine Learning': ['Computer Technology', 'Machine Learning'], 'Graphic Design': ['Graphic Design'], 'Graphic Design|Visual Arts': ['Graphic Design', 'Visual Arts'], 'Education': ['Education'], 'Business|Business Organisation': ['Business', 'Business Organisation'], 'Zoology|Environmental Biology': ['Zoology', 'Environmental Biology'], 'Human Rights|Fundamental Rights': ['Human Rights', 'Fundamental Rights'], 'Computer Technology|Design and Analysis of Algorithms': ['Computer Technology', 'Design and Analysis of Algorithms'], 'Marketing|Marketing Management': ['Marketing', 'Marketing Management'], 'Accounting|Partnership Accounting|Corporate Accounting|Accounting Theory And Practices': ['Accounting', 'Partnership Accounting', 'Corporate Accounting', 'Accounting Theory And Practices'], 'Legal Studies|Income Tax Laws': ['Legal Studies', 'Income Tax Laws'], 'Graphics|Articulation|Computer Creation': ['Graphics', 'Articulation', 'Computer Creation'], 'Archeology|Human Prehistory': ['Archeology', 'Human Prehistory'], 'Business|Start Ups|Entreperneurship|Business Strategies|Venture Capitalist|Business Planning': ['Business', 'Start Ups', 'Entreperneurship', 'Business Strategies', 'Venture Capitalist', 'Business Planning'], 'Geography|Indian Geography': ['Geography', 'Indian Geography'], 'E Commerce|Shopping Platform|Other Online Platforms|Digital India': ['E Commerce', 'Shopping Platform', 'Other Online Platforms', 'Digital India'], 'Business|Bio-entrepreneurship': ['Business', 'Bio-entrepreneurship'], 'Literature|Stories': ['Literature', 'Stories'], 'History|Indian History': ['History', 'Indian History'], 'ViDEO': ['ViDEO'], 'Management|Business Management': ['Management', 'Business Management'], 'Visual Arts|Photography': ['Visual Arts', 'Photography'], 'Social Work|Health Education': ['Social Work', 'Health Education'], 'Social Work|Social Tech': ['Social Work', 'Social Tech'], 'Social Work|Humanities': ['Social Work', 'Humanities'], 'Photography|Visual Arts': ['Photography', 'Visual Arts'], 'Accounting|Financial Accounting': ['Accounting', 'Financial Accounting'], 'Psycholgy|Social Psychology': ['Psycholgy', 'Social Psychology'], 'Photography|Conceptual': ['Photography', 'Conceptual'], 'Physics|Instrumentation': ['Physics', 'Instrumentation'], 'Craft work': ['Craft work'], 'Social Work|Social Interventions|Substance Abuse': ['Social Work', 'Social Interventions', 'Substance Abuse'], 'Economics|Indian Economy': ['Economics', 'Indian Economy'], 'Social Work|Substance Abuse|Social Interventions|Humanities': ['Social Work', 'Substance Abuse', 'Social Interventions', 'Humanities'], 'Social Work|Social Interventions|Substance Abuse|Health Education': ['Social Work', 'Social Interventions', 'Substance Abuse', 'Health Education'], 'Social Work|Humanities|Social Interventions': ['Social Work', 'Humanities', 'Social Interventions'], 'Finance|Financial Analysis': ['Finance', 'Financial Analysis'], 'Architecture': ['Architecture'], 'Photography|Architecture|Painting': ['Photography', 'Architecture', 'Painting'], 'Computer Technology|Cloud Computing|Artificial Intelligence|Information Technology|Programming languages': ['Computer Technology', 'Cloud Computing', 'Artificial Intelligence', 'Information Technology', 'Programming languages'], 'Computer Technology|Design and Analysis of Algorithms|Web designing|Database Management|Artificial Intelligence': ['Computer Technology', 'Design and Analysis of Algorithms', 'Web designing', 'Database Management', 'Artificial Intelligence'], 'Literature|Movements in Literature': ['Literature', 'Movements in Literature'], 'Physics|Atomic Physics|Energy Physics|Quantum Mecahnics|Instrumentation': ['Physics', 'Atomic Physics', 'Energy Physics', 'Quantum Mecahnics', 'Instrumentation'], 'Business|Business Strategies|Venture Capitalist': ['Business', 'Business Strategies', 'Venture Capitalist'], 'Photography|Architecture|Illustration': ['Photography', 'Architecture', 'Illustration'], 'Photography|Architecture': ['Photography', 'Architecture'], 'Human Rights|Fundamental Rights|Protection & Enforcement': ['Human Rights', 'Fundamental Rights', 'Protection & Enforcement'], 'Environment Studies|Pollution|Environmental Biology': ['Environment Studies', 'Pollution', 'Environmental Biology'], 'Photography|Conceptual|Illustration': ['Photography', 'Conceptual', 'Illustration'], 'Physics|Quantum Mecahnics|Industrial Instrumentation|Atomic Physics|Nuclear & Particle Physics|Energy Physics': ['Physics', 'Quantum Mecahnics', 'Industrial Instrumentation', 'Atomic Physics', 'Nuclear & Particle Physics', 'Energy Physics'], 'Biotechnology|Environmental Biotechnology': ['Biotechnology', 'Environmental Biotechnology'], 'Legal Studies|Alternate Dispute Resolution|International Treaties|International Agreement': ['Legal Studies', 'Alternate Dispute Resolution', 'International Treaties', 'International Agreement'], 'Marketing|Principles Of Marketing|Marketing Research Methadology|Marketing Management|International Marketing': ['Marketing', 'Principles Of Marketing', 'Marketing Research Methadology', 'Marketing Management', 'International Marketing'], 'Sculptures': ['Sculptures'], 'Psycholgy|Child Development': ['Psycholgy', 'Child Development'], 'Economics|Economic Policies|Break even Point|Foreign Economy': ['Economics', 'Economic Policies', 'Break even Point', 'Foreign Economy'], 'Psycholgy|Psychological Growth': ['Psycholgy', 'Psychological Growth'], 'Management|Business Management|Technology Mangement|Managerial Activity|Creative And Lateral Management': ['Management', 'Business Management', 'Technology Mangement', 'Managerial Activity', 'Creative And Lateral Management'], 'Business': ['Business'], 'Business|Business Strategies|Business Enviorment|New Venture Planning|Foreign Business|Business Organisation': ['Business', 'Business Strategies', 'Business Enviorment', 'New Venture Planning', 'Foreign Business', 'Business Organisation'], 'Marketing|Principles Of Marketing|International Marketing|Promotion And Distribution Decisions': ['Marketing', 'Principles Of Marketing', 'International Marketing', 'Promotion And Distribution Decisions'], 'Social Work|NGO': ['Social Work', 'NGO'], 'Fine Arts|Painting': ['Fine Arts', 'Painting'], 'Legal Studies|Legal System|Legal Tradition|Nationality Law|Government Law': ['Legal Studies', 'Legal System', 'Legal Tradition', 'Nationality Law', 'Government Law'], 'Business|Entreperneurship|Venture Capitalist|Business Enviorment|Start Ups|Business Planning|New Venture Planning': ['Business', 'Entreperneurship', 'Venture Capitalist', 'Business Enviorment', 'Start Ups', 'Business Planning', 'New Venture Planning'], 'Legal Studies|Company Law|Legal System|Banking Law': ['Legal Studies', 'Company Law', 'Legal System', 'Banking Law'], 'Computer Technology|Web designing|Artificial Intelligence|Computer Application|Machine Learning|Frontend Development': ['Computer Technology', 'Web designing', 'Artificial Intelligence', 'Computer Application', 'Machine Learning', 'Frontend Development'], 'Music': ['Music'], 'Sculptures|Wood Crafts|Craft|Wood carving': ['Sculptures', 'Wood Crafts', 'Craft', 'Wood carving'], 'Fashion Design': ['Fashion Design'], 'Painting|Craft|Artistic design': ['Painting', 'Craft', 'Artistic design'], '2D Composition|Watercolours|Painting': ['2D Composition', 'Watercolours', 'Painting'], 'Painting|Watercolours|2D Composition': ['Painting', 'Watercolours', '2D Composition'], 'Visual Arts|Craft|Conceptual': ['Visual Arts', 'Craft', 'Conceptual'], 'Painting|Visual Arts|Craft|Conceptual': ['Painting', 'Visual Arts', 'Craft', 'Conceptual'], 'Painting|Craft|Mixed Media|2D Composition': ['Painting', 'Craft', 'Mixed Media', '2D Composition'], 'Visual Arts|Craft|Mixed Media|Conceptual|Mosaic painting': ['Visual Arts', 'Craft', 'Mixed Media', 'Conceptual', 'Mosaic painting'], 'Craft|Drawings|Conceptual|2D Composition': ['Craft', 'Drawings', 'Conceptual', '2D Composition'], 'Craft|Mixed Media|Conceptual|Mosaic painting|2D Composition': ['Craft', 'Mixed Media', 'Conceptual', 'Mosaic painting', '2D Composition'], 'Video': ['Video'], 'Fashion Desigining|Fashion Illustration|Pattern Cutting|Fashion Communication': ['Fashion Desigining', 'Fashion Illustration', 'Pattern Cutting', 'Fashion Communication'], 'Biotechnology|Animal Biotechnology': ['Biotechnology', 'Animal Biotechnology'], 'Fashion Desigining|Pattern & Culture|Fashion Trends|Fashion Portfoilio': ['Fashion Desigining', 'Pattern & Culture', 'Fashion Trends', 'Fashion Portfoilio'], 'Sketch Video': ['Sketch Video'], 'Fashion Desigining|Pattern & Culture|Fashion Textile|Fashion Trends': ['Fashion Desigining', 'Pattern & Culture', 'Fashion Textile', 'Fashion Trends'], 'Test': ['Test'], 'Professionalism': ['Professionalism'], 'Art': ['Art'], 'Science;Technology': ['Science;Technology'], 'Art; Science': ['Art; Science'], 'Fashion Design|Illustration|Watercolours|Drawings': ['Fashion Design', 'Illustration', 'Watercolours', 'Drawings'], 'Drawings|Fashion Design|Illustration|Watercolours': ['Drawings', 'Fashion Design', 'Illustration', 'Watercolours'], 'Fashion Design|Illustration|Watercolours': ['Fashion Design', 'Illustration', 'Watercolours'], 'Drawings|Fashion Design|Mixed Media|Conceptual|Illustration|Pen and ink|Watercolours': ['Drawings', 'Fashion Design', 'Mixed Media', 'Conceptual', 'Illustration', 'Pen and ink', 'Watercolours'], 'Fashion Design|Illustration|Conceptual|Watercolours|Pen and ink': ['Fashion Design', 'Illustration', 'Conceptual', 'Watercolours', 'Pen and ink'], 'Artistic design|Logo Design|Graphic|Illustration': ['Artistic design', 'Logo Design', 'Graphic', 'Illustration'], 'Visual Arts|Graphic Design|Artistic design|Graphic|Illustration': ['Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Illustration'], 'Learning': ['Learning'], 'Photography|Architecture|Visual Arts|Graphic Design': ['Photography', 'Architecture', 'Visual Arts', 'Graphic Design'], 'Photography|Architecture|Visual Arts|Graphic Design|Artistic design|Graphic|Logo Design': ['Photography', 'Architecture', 'Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Logo Design'], 'Visual Arts|Graphic Design|2D Composition|Logo Design': ['Visual Arts', 'Graphic Design', '2D Composition', 'Logo Design'], 'Artistic design': ['Artistic design'], 'Literature|Stories|Fictions|Movements in Literature': ['Literature', 'Stories', 'Fictions', 'Movements in Literature'], 'Technology': ['Technology'], 'Computer Technology|Computation|Computer Application|Cloud Computing': ['Computer Technology', 'Computation', 'Computer Application', 'Cloud Computing'], 'Visual Arts|Calligraphy|Pen a

In [21]:
update_data = []
for i in cat:
    dummy = post[post['category'] == i]
    id = dummy['_id'].values[0]
    title = dummy['title'].values[0]
    post_type = dummy[' post_type'].values[0]
    for j in cat[i]:
        dict1 = {}
        dict1.update({'_id': id})
        dict1.update({'title': title})
        dict1.update({'category': j})
        dict1.update({' post_type': post_type})
        update_data.append(dict1)

In [22]:
post1 = pd.DataFrame(update_data)
post1.head()

,_id,title,category,post_type
0,5d62abaa65218653a132c956,hello there,Plant Biotechnology,blog
1,5d6d39567fa40e1417a4931c,Ml and AI,Artificial Intelligence,blog
2,5d6d39567fa40e1417a4931c,Ml and AI,Machine Learning,blog
3,5d6d39567fa40e1417a4931c,Ml and AI,Information Technology,blog
4,5d7d23315720533e15c3b1ee,What is an Operating System ?,Operating Systems,blog

In [23]:
post1.shape

(592, 4)

In [27]:
len(post1['category'].unique().tolist())

235

In [29]:
view.columns.tolist()

['user_id', 'post_id', 'timestamp']

In [30]:
post1.columns.tolist()

['_id', 'title', 'category', ' post_type']

In [31]:
user.columns.tolist()

['_id', 'name', 'gender', 'academics']

In [32]:
post1.rename(columns={'_id' : 'post_id'}, inplace=True)

In [33]:
post1.columns.tolist()

['post_id', 'title', 'category', ' post_type']

In [34]:
user.rename(columns={'_id' : 'user_id'}, inplace=True)

In [35]:
main = pd.merge(view, post1, on='post_id', how='inner')

In [36]:
main.columns.tolist()

['user_id', 'post_id', 'timestamp', 'title', 'category', ' post_type']

In [37]:
main.head()

,user_id,post_id,timestamp,title,category,post_type
0,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Visual Arts,artwork
1,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Graphic Design,artwork
2,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Artistic design,artwork
3,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Graphic,artwork
4,5df49b32cc709107827fb3c7,5ec821ddec493f4a2655889e,2020-06-01T10:46:45.131Z,Save Earth.,Illustration,artwork

In [38]:
main.info()

<class 'pandas.DataFrame'>
RangeIndex: 1752 entries, 0 to 1751
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   user_id     1752 non-null   str
 1   post_id     1752 non-null   str
 2   timestamp   1752 non-null   str
 3   title       1752 non-null   str
 4   category    1752 non-null   str
 5    post_type  1752 non-null   str
dtypes: str(6)
memory usage: 286.8 KB

In [39]:
main.describe()

,user_id,post_id,timestamp,title,category,post_type
count,1752,1752,1752,1752,1752,1752
unique,88,232,628,228,235,4
top,5d60098a653a331687083238,5ec7abfdec493f4a26558860,2020-05-29T20:58:08.018Z,FASHION ILLUSTRATION (OP ART),Illustration,blog
freq,262,63,7,63,78,846

### Моделирование (совместная и контентная фильтрация)

In [40]:
users = list(main['user_id'].unique())
categories = list(main['category'].unique())

### Создание матрицы пользователи-категории

In [41]:
user_mat = [[] for i in range(len(users))]
for i in range(len(users)):
    for j in range(len(categories)):
        value = len(main[(main['user_id'] == users[i]) & (main['category'] == categories[j])])
        user_mat[i].append(value)

In [44]:
for i in user_mat[0]:
    print(i, end=' ')

4 3 3 3 2 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 2 2 2 0 0 0 0 1 2 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

In [45]:
from scipy.sparse import csr_matrix
user_mat = csr_matrix(user_mat)

In [46]:
user_mat

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 1036 stored elements and shape (88, 235)>

In [ ]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(metric='cosine', algorithm='brute', n_neighbors=15)

In [ ]:
model.fit(user_mat)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=15)

In [64]:
def recommender(user_id, data=user_mat, model=model):
    model.fit(data)
    index = users.index(user_id)
    current_user = main[main['user_id'] == user_id]
    distances, indices = model.kneighbors(data[index], 15)
    recomendations = set()
    for i in indices[0]:
        user = main[main['user_id'] == users[i]]
        for j in user['category'].unique():
            if i not in current_user['category'].unique():
                recomendations.add(j)
    return list(recomendations)

In [56]:
users[34]

'5e26bb482a37d20505da2c10'

In [65]:
main[main['user_id'] == users[34]]['category'].unique().tolist()

['Business',
 'Business Skills',
 'Electronics & electrical Technology',
 'Electrical Machines',
 'HR Management',
 'Mathematics',
 'Linear Algebra',
 'Human Resources']

In [68]:
main[main['user_id'] == users[34]]['category'].unique().tolist()

['Business',
 'Business Skills',
 'Electronics & electrical Technology',
 'Electrical Machines',
 'HR Management',
 'Mathematics',
 'Linear Algebra',
 'Human Resources']

In [71]:
recommender(users[34])[:10]

['Fashion Techniques',
 'Fashion Communication',
 'Ceramics',
 'Child Development',
 'Quantum Mecahnics',
 'NGO',
 'International Marketing',
 'Substance Abuse',
 'Advertising',
 'Learning']

In [75]:
post.columns

Index(['_id', 'title', 'category', ' post_type'], dtype='str')

### Контентная фильтрация

In [76]:
posts = list(main['post_id'].unique())

In [80]:
item_profiles = {}
for i in categories:
    item_profiles.update({i:[]})
    for j in posts:
        item_profiles[i].append(1) if i in list(main[main['post_id']==j]['category'].unique()) else item_profiles[i].append(0)

In [84]:
for i in item_profiles:
    item_profiles[i] = np.array(item_profiles[i])

In [85]:
user_profiles = {}
for i in users:
    user_profiles.update({i:[]})
    current_user = main[main["user_id"]==i]
    current_user_categories = list(current_user["category"].unique())
    current_user_post = list(current_user["post_id"].unique())

    category_weight = {}
    result_vector = np.array([0 for i in range(len(posts))])
    for j in current_user_categories:
        category_weight.update({j:0})
        for k in list(current_user["category"]):
            if j == k:
                category_weight[j]+=1
        category_weight[j] = category_weight[j] / len(current_user_post)
        result_vector = result_vector + (category_weight[j]*item_profiles[j])
    user_profiles[i] = result_vector/len(current_user_post)

In [92]:
from sklearn.metrics.pairwise import cosine_similarity

def recommender1(user_id, user_profiles=user_profiles, item_profiles=item_profiles):
    similarity = {}
    for i in item_profiles:
        similarity.update({i:cosine_similarity(user_profiles[user_id].reshape(1, -1), item_profiles[i].reshape(1,-1))})
    sorted_similarity = sorted(similarity.items(), key=lambda x: x[1], reverse=True)
    user_posts = list(main[main['user_id'] == user_id]['title'].unique())
    recommendations = []
    print('Посты просмотренные пользователем:{}'.format(user_posts))
    print('Категории просмотренные пользователем:{}'.format(list(main[main['user_id'] == user_id]['category'].unique())))
    for i in sorted_similarity:
        category_posts = list(main[main['category']==i[0]]['title'].unique())
        for j in category_posts:
            if j not in user_posts:
                recommendations.append([i[0], j])
        if len(recommendations)==20:
            break
    for i in recommendations:
        print(i)

In [96]:
recommender1(users[20])

Посты просмотренные пользователем:['Data Transmission Modes', 'Always Remember !!!', 'EID MUBARAK', 'PHP', 'Quick Sketch of Gangster Skull.', 'Making of Daaku Art', "'The Virtual ME'", 'MIS', 'Operators In PHP', 'Firewall', 'Om Namah Shivaay', 'SEO (Search Engine Optimization)', 'Smart City', 'Making of the Joker sketch', 'Lord shiva (Shadow Drawing)', 'EDI (Electronic data interchange)', 'What is an Operating System ?', 'Lord Shiva', 'E-Commerce', 'E-Commerce - Business Models', 'Hand Art', 'PHP Variables', 'Raster graphics systems', 'Computer Graphics', 'DATA AND MESSAGE SECURITY', 'Stereoscopic and virtual-reality systems', 'Baseband & Broadband', 'Mobile Computing Technology', "Topology & it's types", 'Communication']
Категории просмотренные пользователем:['Computer Technology', 'Computer Application', 'Operating Systems', 'Learning', 'Photography', 'Architecture', 'Visual Arts', 'Graphic Design', 'Artistic design', 'Graphic', 'Logo Design', 'Programming languages', 'Sketch Video', 'Art', 'Fashion Design', 'Illustration', 'Information Technology', 'Hardware', 'Pen and ink', 'Computation', 'Painting', 'Drawing', 'Drawings', 'E Commerce', 'Other Online Platforms', 'E Transactions', 'Shopping Platform', 'Design and Analysis of Algorithms', 'Graphics', 'Computer Creation', 'Mobile Applications', 'Communication', 'Basics of Communiaction']
['Computer Technology', 'Cloud Computing']
['Computer Technology', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Computer Technology', 'Artificial Intelligence']
['Computer Technology', '10 Best UI UX Design Course & Certification [2020]']
['Computer Technology', '8 Best Machine Learning Courses for 2020']
['Computer Technology', 'Operating System 1']
['Computer Technology', '8 Free Data Science Courses & Tutorials [2020]']
['Computer Technology', '7 Best Python Data Science Courses & Certification [2020]']
['Computer Technology', '20 Best Data Science Certification & Courses for 2020']
['Computer Technology', 'What sports will look like in the future']
['Computer Application', 'Cloud Computing']
['Computer Application', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Information Technology', '8 Best Machine Learning Courses for 2020']
['Information Technology', 'Ml and AI']
['Information Technology', 'What sports will look like in the future']
['Artificial Intelligence', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Artificial Intelligence', 'Artificial Intelligence']
['Artificial Intelligence', '10 Best UI UX Design Course & Certification [2020]']
['Artificial Intelligence', '8 Best Machine Learning Courses for 2020']
['Artificial Intelligence', 'Ml and AI']
['Artificial Intelligence', 'What sports will look like in the future']
['Programming languages', '8 Best Machine Learning Courses for 2020']
['Programming languages', 'Python 3 Programming Introduction']
['Computation', 'Cloud Computing']
['Cloud Computing', 'Cloud Computing']
['Cloud Computing', '8 Best Machine Learning Courses for 2020']
['Artistic design', 'Save Earth.']
['Artistic design', 'A solar-powered microbrewery has design-led energy in Sweden']
['Artistic design', 'LGBT PRIDE']
['Artistic design', 'Art Expo 2020']
['Artistic design', 'GLASS PAINTING']
['Artistic design', 'Magazine Cover Redefined']
['Artistic design', 'CONTOURING CLAY']
['Artistic design', 'Traditional and Modern Sports']
['Artistic design', 'Multipurpose Jewel']
['Artistic design', 'The Meenamma']
['Artistic design', 'The Nerd who was thrown out.']
['Visual Arts', 'Save Earth.']
['Visual Arts', 'Acceptance!']
['Visual Arts', 'Eid Mubarak']
['Visual Arts', 'LGBT PRIDE']
['Visual Arts', 'Design Process']
['Visual Arts', 'The girl in the meadow']
['Visual Arts', 'Gun store Logo.']
['Visual Arts', 'Magazine Cover Redefined']
['Visual Arts', 'Best friend']
['Visual Arts', 'PRINCIPLES OF DESIGN (BALANCE)']
['Visual Arts', 'MOSAIC ART']
['Visual Arts', 'PRINCIPLES OF DESIGN ( CONTRAST)']
['Visual Arts', 'The Meenamma']
['Visual Arts', 'Aesthetics']
['Visual Arts', 'gripping']
['Visual Arts', 'Mask: When to use it']
['Visual Arts', 'The Nerd who was thrown out.']
['Design and Analysis of Algorithms', '10 Best UI UX Design Course & Certification [2020]']
['Design and Analysis of Algorithms', '8 Free Data Science Courses & Tutorials [2020]']
['Illustration', 'Save Earth.']
['Illustration', 'FASHION ILLUSTRATION']
['Illustration', 'HUMAN ILLUSTRATION (With Galaxy Background)']
['Illustration', 'FASHION ILLUSTRATION (street fashion)']
['Illustration', 'FASHION ILLUSTRATION (OP ART)']
['Illustration', 'Art Expo 2020']
['Illustration', 'HUMAN ILLUSTRATION ( Background of a room)']
['Illustration', 'The girl in the meadow']
['Illustration', 'Best friend']
['Illustration', 'Q U I E T']
['Illustration', 'Relaxing (Jaisalmer; Rajasthan)']
['Illustration', 'The Nerd who was thrown out.']
['Graphic Design', 'Save Earth.']
['Graphic Design', 'Eid Mubarak']
['Graphic Design', 'Chat App UI Desgin']
['Graphic Design', 'Design Process']
['Graphic Design', 'The girl in the meadow']
['Graphic Design', 'Magazine Cover Redefined']
['Graphic Design', 'Best friend']
['Graphic Design', 'Corporate design']
['Graphic Design', 'Mask: When to use it']
['Graphic Design', 'Disease Prevention']
['Graphic Design', 'The Nerd who was thrown out.']
['Web designing', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Web designing', '10 Best UI UX Design Course & Certification [2020]']
['Machine Learning', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Machine Learning', 'Ml and AI']
['Machine Learning', '7 Best Python Data Science Courses & Certification [2020]']
['Data Science', '20 Best Data Science Certification & Courses for 2020']
['Data Science', 'What sports will look like in the future']
['Operating Systems', 'Operating System 1']
['Graphic', 'Save Earth.']
['Graphic', 'Art Expo 2020']
['Graphic', 'Best friend']
['Graphic', 'Corporate design']
['Frontend Development', '6 Best + Free PLC Programming Training & Course [2020 UPDATED]']
['Drawings', 'HUMAN ILLUSTRATION (With Galaxy Background)']
['Drawings', 'FASHION ILLUSTRATION (OP ART)']
['Drawings', 'HUMAN ILLUSTRATION ( Background of a room)']
['Drawings', 'The girl in the meadow']
['Drawings', 'PRINCIPLES OF DESIGN (RHYTHM)']
['Drawings', 'Portrait art']
['Drawings', 'The Meenamma']
['Drawings', 'Childhood Sketch']
['Drawings', 'The Enlightened Dreams']
['Drawings', 'The Nerd who was thrown out.']
['Drawings', 'Calligraphy']
['Robotics', 'What sports will look like in the future']
['Fashion Design', 'FASHION ILLUSTRATION']
['Fashion Design', 'HUMAN ILLUSTRATION (With Galaxy Background)']
['Fashion Design', 'FASHION ILLUSTRATION (street fashion)']
['Fashion Design', 'FASHION ILLUSTRATION (OP ART)']
['Fashion Design', 'LGBT PRIDE']
['Fashion Design', 'HUMAN ILLUSTRATION ( Background of a room)']
['Fashion Design', 'Magazine Cover Redefined']
['Fashion Design', 'TIE AND DYE']
['Fashion Design', 'Multipurpose Jewel']
['Painting', 'GLASS PAINTING']
['Painting', 'The girl in the meadow']
['Painting', 'Portrait art']
['Painting', 'PRINCIPLES OF DESIGN (CONTRAST)']
['Painting', 'PRINCIPLES OF DESIGN (BALANCE)']
['Painting', 'STRIPS (TINT;TONE AND SHADE)']
['Painting', 'TINT; TONE AND SHADE OF RED']
['Painting', 'Hello world']
['Painting', 'filtered']
['Painting', 'The Meenamma']
['Painting', 'The Enlightened Dreams']
['Painting', 'The Nerd who was thrown out.']
['Database Management', '10 Best UI UX Design Course & Certification [2020]']
['Logo Design', 'Design Process']
['Logo Design', 'Art Expo 2020']
['Photography', 'Eid Mubarak']
['Photography', 'Magazine Cover Redefined']
['Photography', 'Q U I E T']
['Photography', 'filtered']
['Photography', 'Relaxing (Jaisalmer; Rajasthan)']
['Photography', 'Filtered Busy Streets  (Jaisalmer; Raj.)']
['Photography', 'You are one in a kind!']
['Photography', 'Aesthetics']
['Photography', 'gripping']
['Photography', 'Colours of pushkar.']
['Watercolours', 'FASHION ILLUSTRATION']
['Watercolours', 'HUMAN ILLUSTRATION (With Galaxy Background)']
['Watercolours', 'FASHION ILLUSTRATION (street fashion)']
['Watercolours', 'FASHION ILLUSTRATION (OP ART)']
['Watercolours', 'HUMAN ILLUSTRATION ( Background of a room)']
['Watercolours', 'STRIPS (TINT;TONE AND SHADE)']
['Watercolours', 'TINT; TONE AND SHADE OF RED']
['Watercolours', 'The Meenamma']
['Watercolours', 'Childhood Sketch']
['Watercolours', 'The Enlightened Dreams']
['Watercolours', 'Best place in the world']
['Architecture', 'Eid Mubarak']
['Architecture', 'Beauty']
['Architecture', 'filtered']
['Architecture', 'Relaxing (Jaisalmer; Rajasthan)']
['Architecture', 'Filtered Busy Streets  (Jaisalmer; Raj.)']
['E Commerce', 'Benefits of Buying Grocery Online in Twin city of Odisha']
['Prints', 'The girl in the meadow']
['Acrylics', 'The Meenamma']
['Other Online Platforms', 'Benefits of Buying Grocery Online in Twin city of Odisha']
['Conceptual', 'Chat App UI Desgin']
['Conceptual', 'FASHION ILLUSTRATION (street fashion)']
['Conceptual', 'FASHION ILLUSTRATION (OP ART)']
['Conceptual', 'LGBT PRIDE']
['Conceptual', 'MOSAIC ART']
['Conceptual', 'PRINCIPLES OF DESIGN (RHYTHM)']
['Conceptual', 'PRINCIPLES OF DESIGN (BALANCE)']
['Conceptual', 'PRINCIPLES OF DESIGN ( CONTRAST)']
['Conceptual', 'Q U I E T']
['Conceptual', 'You are one in a kind!']
['Conceptual', 'Truth❤💯']
['Conceptual', 'I won the Art.']
['Shopping Platform', 'Benefits of Buying Grocery Online in Twin city of Odisha']
['Craft', 'GLASS PAINTING']
['Craft', 'MOSAIC ART']
['Craft', 'PRINCIPLES OF DESIGN (RHYTHM)']
['Craft', 'PRINCIPLES OF DESIGN (CONTRAST)']
['Craft', 'PRINCIPLES OF DESIGN (BALANCE)']
['Craft', 'Traditional and Modern Sports']
['Craft', 'WOOD CARVING']
['Craft', 'PRINCIPLES OF DESIGN ( CONTRAST)']
['Pen and ink', 'Habit.']
['Pen and ink', 'Moments in life']
['Pen and ink', 'Self belief.']
['Pen and ink', 'Voice of intuition!']
['Pen and ink', 'Change.']
['Pen and ink', 'Acceptance!']
['Pen and ink', 'FASHION ILLUSTRATION (street fashion)']
['Pen and ink', 'FASHION ILLUSTRATION (OP ART)']
['Digital India', 'Benefits of Buying Grocery Online in Twin city of Odisha']
['Ceramics', 'Multipurpose Jewel']
['2D Composition', 'Design Process']
['2D Composition', 'MOSAIC ART']
['2D Composition', 'PRINCIPLES OF DESIGN (RHYTHM)']
['2D Composition', 'PRINCIPLES OF DESIGN (CONTRAST)']
['2D Composition', 'STRIPS (TINT;TONE AND SHADE)']
['2D Composition', 'TINT; TONE AND SHADE OF RED']
['Mixed Media', 'Voice of intuition!']
['Mixed Media', 'SERP Meta Checker | Check Your Meta Preview in SERP | Tools For Search Engine Optimization']
['Mixed Media', 'FASHION ILLUSTRATION (OP ART)']
['Mixed Media', 'MOSAIC ART']
['Mixed Media', 'PRINCIPLES OF DESIGN (CONTRAST)']
['Mixed Media', 'Truth❤💯']
['Calligraphy', 'Habit.']
['Calligraphy', 'Moments in life']
['Calligraphy', 'Voice of intuition!']
['Calligraphy', 'Change.']
['Calligraphy', 'Acceptance!']
['Calligraphy', 'Designs : where magic happens.']
['Calligraphy', 'Calligraphy']
['Graphics', 'Benefits Of A Virtual Portfolio.']
['Computer Creation', 'Benefits Of A Virtual Portfolio.']
['Sculptures', 'Handcrafted']
['Sculptures', 'CONTOURING CLAY']
['Sculptures', 'WOOD CARVING']
['Articulation', 'Benefits Of A Virtual Portfolio.']
['Typography', 'Habit.']
['Typography', 'Moments in life']
['Typography', 'Self belief.']
['Mosaic painting', 'MOSAIC ART']
['Fine Arts', 'Hello world']
['Science; Technology', 'Face Recognition using Transfer Learning.']
['Technology', 'Launching an EC2 instance.']
['Mass Media', 'Success Story Of OYO Founder Ritesh Agarwal']
['Mass Media', 'Netflix: As a Case Study']
['Mass Media', 'Corona: What it is; how to prevent it and its effect on us']
['Mass Media', 'Personal growth']
['Media And Society', 'Success Story Of OYO Founder Ritesh Agarwal']
['Competition Laws', 'How Competition law evolved?']
['Marketing', 'Importance of Digital Marketing for Startups']
['Marketing', 'Benefits of Guest Posting to both Writers and Brand']
['Marketing', 'Innovative Marketing Strategies']
['Marketing', 'How Artificial Intelligence tools Help You To Get Smart In Your Content Marketing']
['Advertising', 'Importance of Digital Marketing for Startups']
['Promotion And Distribution Decisions', 'Benefits of Guest Posting to both Writers and Brand']
['Promotion And Distribution Decisions', 'Innovative Marketing Strategies']
['Digital Marketing', 'Top 10 big benefits of having a digital marketing career']
['Business', 'Guest Posting at Free of Cost']
['Business', 'Analysis Of Successful Companies For the Past 5 years']
['Business', 'Entrepreneural Training: The roadless travel']
['Business', 'Business skills']
['Business', 'Why Do Millennials Change Jobs?']
['Business', 'Ways to Choose the Perfect Tour or Travel Agency/Company in Bhubaneswar']
['Business', 'Theory Of Capital Structure.']
['Business', 'How to Choose the Right Home Cleaning Service Provider']
['Business', 'How To Lead Your Startups After Facing Loses: Case Study']
['Literature', "Here are 7 of my favourite books that I've read so far this year!⠀"]
['Literature', 'Sharing is caring!']
['Literature', 'Creativity During Quarantine?']
['Stories', "Here are 7 of my favourite books that I've read so far this year!⠀"]
['Stories', 'Creativity During Quarantine?']
['Fictions', "Here are 7 of my favourite books that I've read so far this year!⠀"]
['Movements in Literature', "Here are 7 of my favourite books that I've read so far this year!⠀"]
['Movements in Literature', 'Sharing is caring!']
['Art; Science', 'My First Animated Post.']
['Fashion Desigining', 'The 7 Steps of Doing A Professional Design Task.']
['Fashion Desigining', 'Importance of Design.']
['Fashion Desigining', 'The Basic Edge of Design.']
['Fashion Desigining', 'Textile And Apparel Testing']
['Pattern & Culture', 'The 7 Steps of Doing A Professional Design Task.']
['Pattern & Culture', 'Importance of Design.']
['Fashion Trends', 'The 7 Steps of Doing A Professional Design Task.']
['Fashion Trends', 'Importance of Design.']
['Fashion Portfoilio', 'The 7 Steps of Doing A Professional Design Task.']
['Video editing', 'Promotional video.']
['Business Strategies', 'Analysis Of Successful Companies For the Past 5 years']
['Business Strategies', 'Theory Of Capital Structure.']
['Business Strategies', 'How To Lead Your Startups After Facing Loses: Case Study']
['Business Enviorment', 'Analysis Of Successful Companies For the Past 5 years']
['Business Enviorment', 'Entrepreneural Training: The roadless travel']
['New Venture Planning', 'Analysis Of Successful Companies For the Past 5 years']
['New Venture Planning', 'Entrepreneural Training: The roadless travel']
['Foreign Business', 'Analysis Of Successful Companies For the Past 5 years']
['Business Organisation', 'Analysis Of Successful Companies For the Past 5 years']
['Business Organisation', 'Ways to Choose the Perfect Tour or Travel Agency/Company in Bhubaneswar']
['Science;Technology', 'Future Communication Predictions']
['random', 'Library Managment System: Software Requirement Specification (SRS)']
['Political Science', 'Colonialism in India']
['Political Science', 'International Politics']
['Political Science', 'What is Effective Leadership In Politics']
['Political Science', 'Is China lying about Corona']
['Colonialism In India', 'Colonialism in India']
['Legal Studies', 'Labour law']
['Legal Studies', 'BASIC STRUCTURE DOCTRINE']
['Legal Studies', 'Indian Polity And Governance.']
['Legal Studies', 'Corporate Influence']
['Legal Studies', 'Nature of Industrial Disputes.']
['Legal Studies', 'What are Set Off and Carry Forward Losses']
['Labor Law', 'Labour law']
['Banking', 'ROLE OF BANKING COMPANIES IN INDIA']
['Banking', 'WHAT NEW TECHNOLOGY DOES BANKS ARE USING TODAY?']
['Banking Companies', 'ROLE OF BANKING COMPANIES IN INDIA']
['Auditing', 'WHAT IS STATUTORY AUDIT']
['Auditing', 'IMPORTANCE OF INTERNAL FINANCIAL CONTROL']
['Auditing', 'HOW INTERNAL AUDIT WORKS']
['Auditing', 'WHY AUDIT EVIDENCE IS NECESSARY?']
['Auditing', 'SECRETARIAL AUDIT']
['Auditing', 'AUDIT REMARK']
['Auditing', 'WHY COST AUDIT IS IMPORTANT FOR A COMPANY']
['Statuary Audit', 'WHAT IS STATUTORY AUDIT']
['Legal System', 'BASIC STRUCTURE DOCTRINE']
['Legal System', 'Indian Polity And Governance.']
['Legal System', 'Corporate Influence']
['Sports Coaching', 'SPORTS LEGISLATIONS IN INDIA']
['Sports Coaching', 'Will IPL happen this year']
['Sports Law', 'SPORTS LEGISLATIONS IN INDIA']
['Taxation', 'Custom laws']
['Taxation', 'GOODS & SERVICE TAX (GST)']
['Taxation', 'DIRECT TAX']
['Custom Laws', 'Custom laws']
['Economics', 'Concept of Revenue']
['Economics', 'Economics Sociology']
['Economics', 'How will the economy be affected if Nations produce what they eat?']
['Economics', 'INDIA 5 TRILLION ECONOMY']
['Revenue Concept', 'Concept of Revenue']
['Human Rights', 'Human Rights and Duties']
['Human Rights', 'Formation Of Trade Union']
['Human Rights', 'JUSTICE FOR NORTH EAST']
['Rights and Duties', 'Human Rights and Duties']
['Sociology', 'Sociology of Religion']
['Sociology', 'Sociology in India']
['Sociology of Religion', 'Sociology of Religion']
['Sociology in India', 'Sociology in India']
['International Politics', 'International Politics']
['Internal Financial Control', 'IMPORTANCE OF INTERNAL FINANCIAL CONTROL']
['Internal Audit', 'HOW INTERNAL AUDIT WORKS']
['Audit Evidence', 'WHY AUDIT EVIDENCE IS NECESSARY?']
['GST', 'GOODS & SERVICE TAX (GST)']
['Direct Tax', 'DIRECT TAX']
['Secratarial Audit', 'SECRETARIAL AUDIT']
['Banking Technology', 'WHAT NEW TECHNOLOGY DOES BANKS ARE USING TODAY?']
['Audit Remark', 'AUDIT REMARK']
['Cost Audit', 'WHY COST AUDIT IS IMPORTANT FOR A COMPANY']
['Economics Sociology', 'Economics Sociology']
['Professionalism', 'Become professional']
['Fashion Textile', 'Importance of Design.']
['Fashion Textile', 'Textile And Apparel Testing']
['Fashion Illustration', 'The Basic Edge of Design.']
['Pattern Cutting', 'The Basic Edge of Design.']
['Fashion Communication', 'The Basic Edge of Design.']
['Philosophy', 'REAL TALK']
['Philosophy', 'Distracted? Unfocused? Used This Method To Avoid Distraction.']
['Philosophy', 'Sad songs']
['Public Philosophy', 'REAL TALK']
['Test', 'New platform']
['Applied Ethics', 'Distracted? Unfocused? Used This Method To Avoid Distraction.']
['Entreperneurship', 'Entrepreneural Training: The roadless travel']
['Entreperneurship', 'How To Lead Your Startups After Facing Loses: Case Study']
['Venture Capitalist', 'Entrepreneural Training: The roadless travel']
['Venture Capitalist', 'Theory Of Capital Structure.']
['Venture Capitalist', 'How To Lead Your Startups After Facing Loses: Case Study']
['Start Ups', 'Entrepreneural Training: The roadless travel']
['Start Ups', 'How To Lead Your Startups After Facing Loses: Case Study']
['Business Planning', 'Entrepreneural Training: The roadless travel']
['Business Planning', 'How To Lead Your Startups After Facing Loses: Case Study']
['Biotechnology', '5 points to consider while choosing a pathology lab']
['Biotechnology', 'Molecular Biology']
['Biotechnology', 'Gynecology']
['Biotechnology', 'What Can I Do to Keep Myself Safe From Coronavirus ?']
['Biotechnology', '100 Free University Courses Online [2020]']
['Animal Biotechnology', '5 points to consider while choosing a pathology lab']
['Social Work', 'Stand alone and stand apart.']
['Social Work', 'Urdu Poetry']
['Social Work', 'HOW TO THINK DIFFERENTLY?']
['Social Work', 'HOW TO PREPARE YOURSELF FOR A BETTER TOMORROW?']
['Social Work', 'REBEL?']
['Social Work', 'INDIA:- SAVIOR FROM CORONA']
['Social Work', 'IMPORTANCE OF MENTAL HEALTH']
['Social Work', 'CYBER WORLD WAR']
['Humanities', 'Stand alone and stand apart.']
['Humanities', 'HOW TO PREPARE YOURSELF FOR A BETTER TOMORROW?']
['Humanities', 'INDIA:- SAVIOR FROM CORONA']
['Social Interventions', 'Stand alone and stand apart.']
['Social Interventions', 'HOW TO THINK DIFFERENTLY?']